version: '3.3'
services:
  partdb:
    container_name: partdb
    # By default Part-DB will be running under Port 8080, you can change it here
    ports:
      - '8080:80'
    volumes:
      # By default
      - ./uploads:/var/www/html/uploads
      - ./public_media:/var/www/html/public/media
      - ./db:/var/www/html/var/db
    restart: unless-stopped
    image: jbtronics/part-db1:latest
    depends_on:
      - database
    environment:
      - DATABASE_URL=mysql://partdb:${SECRET_USER_PASSWORD}@database:3306/partdb
      # In docker env logs will be redirected to stderr
      - APP_ENV=docker

      # You can configure Part-DB using environment variables
      # Below you can find the most essential ones predefined
      # However you can add add any other environment configuration you want here
      # See .env file for all available options or https://docs.part-db.de/configuration.html

      - DEFAULT_URI=${DEFAULT_URI}
    
      # The language to use serverwide as default (en, de, ru, etc.)
      - DEFAULT_LANG=en
      # The default timezone to use serverwide (e.g. Europe/Berlin)
      - DEFAULT_TIMEZONE=Europe/Berlin
      # The currency that is used inside the DB (and is assumed when no currency is set). This can not be changed later, so be sure to set it the currency used in your country
      - BASE_CURRENCY=EUR
      # The name of this installation. This will be shown as title in the browser and in the header of the website
      - INSTANCE_NAME=Part-DB

      # Allow users to download attachments to the server by providing an URL
      # This could be a potential security issue, as the user can retrieve any file the server has access to (via internet)
      - ALLOW_ATTACHMENT_DOWNLOADS=0
      # Use gravatars for user avatars, when user has no own avatar defined
      - USE_GRAVATAR=0

      # Override value if you want to show to show a given text on homepage.
      # When this is empty the content of config/banner.md is used as banner
      - BANNER=Welcome<br>with a line break

      - PROVIDER_LCSC_ENABLED=1
      - PROVIDER_DIGIKEY_CLIENT_ID=${PROVIDER_DIGIKEY_CLIENT_ID}
      - PROVIDER_DIGIKEY_SECRET=${PROVIDER_DIGIKEY_SECRET}
      - PROVIDER_TME_KEY=${PROVIDER_TME_KEY}
      - PROVIDER_TME_SECRET=${PROVIDER_TME_SECRET}
      - PROVIDER_MOUSER_KEY=${PROVIDER_MOUSER_KEY}
      - PROVIDER_MOUSER_SEARCH_LIMIT=${PROVIDER_MOUSER_SEARCH_LIMIT}
      - PROVIDER_MOUSER_SEARCH_OPTION=${PROVIDER_MOUSER_SEARCH_OPTION}
      - PROVIDER_OCTOPART_CLIENT_ID=${PROVIDER_OCTOPART_CLIENT_ID}
      - PROVIDER_OCTOPART_SECRET=${PROVIDER_OCTOPART_SECRET}

      - EDA_KICAD_CATEGORY_DEPTH=${EDA_KICAD_CATEGORY_DEPTH}

  database:
    container_name: partdb_database
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${SECRET_ROOT_PASSWORD}
      MYSQL_DATABASE: partdb
      MYSQL_USER: partdb
      MYSQL_PASSWORD: ${SECRET_USER_PASSWORD}
    # Uncomment the following line if you need to access, your MySQL database from outside of docker (e.g. for debugging), normally you should leave that disabled
    #ports:
    #  - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

